### ISSUE TITLE
TickCentral conflict

### ISSUE THREAD

**Issue by democat3457** [Focamacho/DupeFix-Project#96] opened 2021-08-02 01:00 UTC
Crash when updating from 3.1.2 to 3.1.3+ (includes 3.1.4)
[crash-2021-08-01_19.57.37-client.txt](https://github.com/Focamacho/DupeFix-Project/files/6913777/crash-2021-08-01_19.57.37-client.txt)

Quark version used: (r183) https://www.curseforge.com/minecraft/mc-mods/quark-rotn-edition/files/3351777
Quark RotN GitHub: https://github.com/Rebirth-of-the-Night/Quark

**Comment by focamacho** [comment] 2021-08-03 14:54
It seems that the problem is the TickCentral, not quark

**Comment by focamacho** [comment] 2021-08-03 14:57
Should be fixed in the latest release. Thanks for the report!

**Closed as completed by focamacho** 2021-08-03 14:57 UTC
Labels: bug
