### ISSUE TITLE
Your mod will not run - Config need to accept empty values/or false

### ISSUE THREAD

**Issue by Petschko** [Focamacho/DupeFix-Project#51] opened 2020-10-25 10:46 UTC
Hey,

I tried to get your mod to run, I added the Jar-Files to the config. But my Problem is, I dont have all mods installed which you fix. So i tried to leave the values of the non-installed mods `""` or `false`, even removed the lines one time. But your mod will always crash and want me to put in these values.

For me its therefore unusable, but I thought you're may interested in that behavior. If there is a option to ignore uninstalled mods, you should add it to your wiki page how to set this in the config. I couldn't figure out^^

Thanks for your work =)

Petschko

**Comment by focamacho** [comment] 2020-10-25 13:57
Hello. If you don't have the mod installed you can just leave the value empty.
Make sure you have added the mod names on the right line, otherwise it will crash.
If you are still having errors, show your configuration file and the crash report.

**Comment by Petschko** [comment] 2020-10-25 18:03
Here is the message with the crash log

Config:
```
{
    "netherChest": "",
    "bloodMagic": "",
    "industrialForegoing": "",
    "actuallyAdditions": "",
    "thaumcraft": "Thaumcraft-1.12.2-6.1.BETA26.jar",
    "extraUtilities": "extrautils2-1.12-1.9.9.jar",
    "tinyProgressions": "",
    "theFarlanders": "",
    "enderio": "EnderIO-1.12.2-5.2.61.jar",
    "_comment": "Visit the wiki to learn how to configure it: https://github.com/Focamacho/DupeFix-Project/wiki",
    "thaumicWonders": "",
    "spiceOfLife": ""
}
```

```
[19:00:58] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/Peter/Downloads/Serenetity%20Online%20Server/./mods/DupeFixProject-1.12.2-3.0.3.jar Service=LaunchWrapper Env=SERVER
[19:00:58] [main/WARN] [FML]: The coremod DupeFixProjectCoreMod (com.focamacho.dupefixproject.asm.DupeFixProjectCoreMod) is not signed!
[19:00:58] [main/ERROR] [DupeFix Project]: Couldn't load fixes for Blood Magic. If the mod is present, check your configuration file.
[19:00:58] [main/ERROR] [DupeFix Project]: Couldn't load fixes for Nether Chest. If the mod is present, check your configuration file.
[19:00:58] [main/ERROR] [DupeFix Project]: Couldn't load fixes for Spice of Life. If the mod is present, check your configuration file.
[19:00:58] [main/INFO] [DupeFix Project]: Initializing Thaumcraft Fixes
[19:00:58] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[19:00:58] [main/ERROR] [DupeFix Project]: Couldn't load fixes for Tiny Progressions. If the mod is present, check your configuration file.
[19:00:58] [main/ERROR] [DupeFix Project]: Couldn't load fixes for Industrial Foregoing. If the mod is present, check your configuration file.
[19:00:58] [main/ERROR] [DupeFix Project]: Couldn't load fixes for Actually Additions. If the mod is present, check your configuration file.
[19:00:58] [main/INFO] [DupeFix Project]: Initializing Extra Utilities Fixes
[19:00:58] [main/ERROR] [DupeFix Project]: Couldn't load fixes for The Farlanders. If the mod is present, check your configuration file.
[19:00:58] [main/ERROR] [DupeFix Project]: Couldn't load fixes for Thaumic Wonders. If the mod is present, check your configuration file.
[19:00:58] [main/INFO] [LaunchWrapper]: Loading tweak class name com.forgeessentials.core.preloader.FELaunchHandler
[19:00:58] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[19:00:58] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:00:58] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:00:58] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:00:58] [main/INFO] [TickProfiler]: TickProfiler v1.12-0.0.7 coremod injectData called, loading patches
[19:00:58] [main/INFO] [ModPatcher]: ModPatcher running under classloader net.minecraft.launchwrapper.LaunchClassLoader
[19:00:58] [main/INFO] [JavaPatcher]: Added patch minecraft: Patcher.ClassPatchDescriptor(name=net.minecraft.world.World, patches=[Patcher.PatchDescriptor(methods=func_72939_s()V, patch=clone), Patcher.PatchDescriptor(methods=func_72939_s()V, patch=insertCodeBefore), Patcher.PatchDescriptor(methods=updateEntities_withProfiling(), patch=replaceMethodCall), Patcher.PatchDescriptor(methods=updateEntities_withProfiling(), patch=replaceMethodCall), Patcher.PatchDescriptor(methods=updateEntities_withProfiling(), patch=replaceMethodCall), Patcher.PatchDescriptor(methods=updateEntities_withProfiling(), patch=replaceMethodCall), Patcher.PatchDescriptor(methods=updateEntities_withProfiling(), patch=replaceMethodCall)])
[19:00:58] [main/INFO] [JavaPatcher]: Added patch minecraft: Patcher.ClassPatchDescriptor(name=net.minecraft.network.play.server.SPacketCustomPayload, patches=[Patcher.PatchDescriptor(methods=, patch=addMethod)])
[19:00:58] [main/INFO] [JavaPatcher]: Added patch minecraft: Patcher.ClassPatchDescriptor(name=net.minecraft.network.NettyPacketEncoder, patches=[Patcher.PatchDescriptor(methods=encode(Lio/netty/channel/ChannelHandlerContext;Lnet/minecraft/network/Packet;Lio/netty/buffer/ByteBuf;)V, patch=replaceMethodCall)])
[19:00:58] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:00:59] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[19:00:59] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:00:59] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:00:59] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:01:00] [main/INFO] [LaunchWrapper]: Calling tweak class codechicken.asm.internal.Tweaker
[19:01:00] [main/INFO] [STDOUT]: [codechicken.asm.internal.Tweaker:injectIntoClassLoader:30]: false
[19:01:00] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[19:01:00] [main/INFO] [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@7063686f
[19:01:00] [main/INFO] [LaunchWrapper]: Calling tweak class com.forgeessentials.core.preloader.FELaunchHandler
[19:01:00] [main/WARN] [mixin]: MixinEnvironment::setCompatibilityLevel is deprecated and will be removed. Set level via config instead!
[19:01:00] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: java.lang.reflect.InvocationTargetException
[19:01:00] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:01:00] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[19:01:00] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:01:00] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[19:01:00] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
[19:01:00] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
[19:01:00] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: Caused by: java.lang.NoSuchMethodError: org.spongepowered.asm.launch.platform.MixinPlatformManager.addContainer(Ljava/net/URI;)Lorg/spongepowered/asm/launch/platform/MixinContainer;
[19:01:00] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at com.forgeessentials.core.preloader.FELaunchHandler.acceptOptions(FELaunchHandler.java:91)
[19:01:00] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:114)
[19:01:00] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:01:00] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	... 6 more
```

without your mod everything loads fine

PS: I tried to use Version 3.0.3 of your mod~

**Comment by focamacho** [comment] 2020-10-25 18:46
This may be caused by another mod loading an outdated version of Mixin. Probably ForgeEssentials.
Make sure you are using the latest version of ForgeEssentials (12.3.83).

**Comment by focamacho** [comment] 2020-11-02 02:50
I will close this issue, if the problem persists let me know.

**Closed as completed by focamacho** 2020-11-02 02:50 UTC
